name: Build RM2100 R2100

on: 
  release:
    types: [published]
#  push:
#    tags:
#    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 17 * * 4
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        cd toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: "RM2100 NEWIFI3"
      run: |
        cwd=`pwd`
        CONFIG_TOOLCHAIN_DIR=${cwd//\//\\\/}\\/toolchain-mipsel
        cd trunk
        for m in $TNAME;
        do
        if [ ! -f configs/templates/$m.config ] ; then
        echo "configs/templates/$m.config not found "
        exit 1
        fi
        cp -f configs/templates/$m.config .config
        #####################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #åˆ é™¤é…ç½®é¡¹MENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config #åˆ é™¤é…ç½®é¡¹SOFTETHERVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config #åˆ é™¤é…ç½®é¡¹SOFTETHERVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config #åˆ é™¤é…ç½®é¡¹SOFTETHERVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #åˆ é™¤é…ç½®é¡¹SCUTCLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #åˆ é™¤é…ç½®é¡¹SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #åˆ é™¤é…ç½®é¡¹SS server
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #åˆ é™¤é…ç½®é¡¹DNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #åˆ é™¤é…ç½®é¡¹adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #åˆ é™¤é…ç½®é¡¹adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #åˆ é™¤é…ç½®é¡¹adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #åˆ é™¤é…ç½®é¡¹adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #åˆ é™¤é…ç½®é¡¹é˜¿é‡ŒDDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
        ######################################################################
        ##ç§‘å­¦ä¸Šç½‘##
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config #ç§‘å­¦ä¸Šç½‘æ’ä»¶ï¼Œé€‰æ‹©nåå…¨éƒ¨æœ‰å…³æ’ä»¶éƒ½ä¸é›†æˆ
        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #é›†æˆv2rayæ‰§è¡Œæ–‡ä»¶ï¼Œå¦‚æœä¸é›†æˆï¼Œä¼šä»ç½‘ä¸Šä¸‹è½½ä¸‹æ¥æ‰§è¡Œï¼Œä¸å½±å“æ­£å¸¸ä½¿ç”¨
        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config #é›†æˆtrojanæ‰§è¡Œæ–‡ä»¶ï¼Œå¦‚æœä¸é›†æˆï¼Œä¼šä»ç½‘ä¸Šä¸‹è½½ä¸‹æ¥æ‰§è¡Œï¼Œä¸å½±å“æ­£å¸¸ä½¿ç”¨
        echo "CONFIG_FIRMWARE_INCLUDE_KUMASOCKS=n" >> .config #socks5æœåŠ¡ç«¯
        ##ç§‘å­¦ä¸Šç½‘##
        ##å¹¿å‘Šç®¡ç†##
        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config #adbyby plus+
        echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config #KPå¹¿å‘Šè¿‡æ»¤
        ##å¹¿å‘Šç®¡ç†##
        ##DNSæœåŠ¡##
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> .config #smartdns
        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config #adg DNSå»AD
        ##DNSæœåŠ¡##
        ##æ–‡ä»¶ç®¡ç†##
        echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config #åœ¨çº¿æ–‡ä»¶ç®¡ç†æœåŠ¡
        echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config #é›†æˆcadduæ‰§è¡Œæ–‡ä»¶ï¼Œæ­¤æ–‡ä»¶æœ‰13M,è¯·æ³¨æ„å›ºä»¶å¤§å°ã€‚å¦‚æœä¸é›†æˆï¼Œä¼šä»ç½‘ä¸Šä¸‹è½½ä¸‹æ¥æ‰§è¡Œï¼Œä¸å½±å“æ­£å¸¸ä½¿ç”¨
        ##æ–‡ä»¶ç®¡ç†##
        ##éŸ³ä¹è§£é”##
        echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config #ç½‘æ˜“äº‘è§£é”
        echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config #ç½‘æ˜“äº‘è§£é”GOç‰ˆæœ¬æ‰§è¡Œæ–‡ä»¶ï¼ˆ2Må¤šï¼‰æ³¨æ„å›ºä»¶è¶…å¤§å°
        ##éŸ³ä¹è§£é”##
        ##å†…ç½‘ç©¿é€æœåŠ¡##
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config #aliddns
        ##å†…ç½‘ç©¿é€æœåŠ¡##
        ####################################################################################
        sed -i "s/^CONFIG_TOOLCHAIN_DIR=.*$/CONFIG_TOOLCHAIN_DIR=${CONFIG_TOOLCHAIN_DIR}/g" .config
        sudo ./clear_tree_simple
        sudo ./build_firmware_modify $m 0
        sudo mv -f images/*.trx /opt/images/
        done
        
    - name: WeChat notification
      if: env.SCKEY
      run: |
        [ steps.compile.outputs.status == 'success' ] && curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=ğŸ‰Padavanç¼–è¯‘å®ŒæˆğŸ˜‹|| curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=âŒPadavanç¼–è¯‘å¤±è´¥ğŸ˜©
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.R_TOKEN }}
        file: /opt/images/*.trx
        tag: AtuoBuild
        overwrite: true
        file_glob: true
    
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
